---
- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ loop_vars }}"
  loop: "{{ query('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distro }}-{{ ansible_distro_version }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_release }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_major_version }}.yml"
        - "{{ ansible_distro }}.yml"
        - "{{ ansible_os_family | lower }}-family.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "vars"
      skip: true
  loop_control:
    loop_var: loop_vars

- name: Make a sudo file
  vars:
    sudoers_merged: "{{ sudoers | default([]) + sudoers_all | default([]) }}"
  ansible.builtin.template:
    src: 'sudoers.j2'
    dest: "{{ sudoers_dir }}/{{ '20_' + item.user + '_' + item.name }}"
    owner: root
    group: root
    mode: 0440
    validate: "visudo -cf %s"  # {{ sudoers_dir }}/{{ '20' + item.user + '_' + item.name }}"
  loop: "{{ sudoers_merged }}"
  when: (sudoers is defined) or (sudoers_all is defined)
