---
- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ loop_vars }}"
  loop: "{{ query('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distro }}-{{ ansible_distro_version }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_release }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_major_version }}.yml"
        - "{{ ansible_distro }}.yml"
        - "{{ ansible_os_family | lower }}-family.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "vars"
      skip: true
  loop_control:
    loop_var: loop_vars

- name: Debug
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.template', 'sudoers.j2') }}"
  loop: "{{ sudo_rights | dict2items }}"

- name: Attempting to overlay sudoers.d configurations, if applicable
  ansible.builtin.template:
    src: sudoers.j2
    dest: "{{ sudo_sudoers_dir }}/{{ item.key }}"
    owner: root
    group: root
    mode: 0440
    validate: 'visudo -cf %s'
  loop: "{{ sudo_rights | dict2items }}"
