---
- name: Converge
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: Create users
      ansible.builtin.user:
        state: present
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        create_home: true
        shell: "/bin/bash"
      loop:
        - name: "firstusersudo"
          comment: "first user for test sudo role"
        - name: "secondusersudo"
          comment: "second user for test sudo role"

  vars:
    sudo_purge_others_config: true

    sudo_user_aliases:
      test: ["secondusersudo", "firstusersudo"]

    sudo_command_aliases:
      SHUTDOWN: ["/usr/sbin/reboot", "/usr/sbin/poweroff"]
      FILTER: ["/usr/sbin/grep", "/usr/sbin/fgrep", "/usr/sbin/egrep"]

    sudo_rights:
      allowrebootandfilter:
        - name: "TEST"
          no_passwd: true
          from_hosts: ALL
          as_user: ALL
          as_group: ALL
          commands: SHUTDOWN
          state: present
        - name: "secondusersudo"
          no_passwd: true
          from_hosts: ALL
          as_user: ALL
          as_group: ALL
          commands: FILTER
          state: present
      allowfirstusertail:
        - name: "firstusersudo"
          no_passwd: true
          from_hosts: ALL
          as_user: ALL
          as_group: ALL
          commands:
            - /usr/bin/tail /dev/null
          state: present

  roles:
    - role: claranet.sudo
      become: true
