---
- name: Converge
  hosts: all

  pre_tasks:
    # - name: create test users
    #   ansible.builtin.user:
    #     state: present
    #     name: firstusersudo
    #     password: first
    #     comment: "first user for test sudo role"
    #     create_home: true
    #     shell: /bin/bash

    # - name: create group test
    #   ansible.builtin.group:
    #     name: grouptestsudo
    #     state: present

    # - name: create second test users
    #   ansible.builtin.user:
    #     state: present
    #     name: secondusersudo
    #     password: second
    #     comment: "second user for test sudo role"
    #     create_home: true
    #     shell: /bin/bash

  vars:
    sudo_rights:
      secondusersudo:
        - name: "secondusersudo"
          no_passwd: false
          from_hosts: ALL
          as_user: ALL
          as_group: ALL
          commands: SHUTDOWN
          state: present
  
      firstgroupsudo:
        - name: "%firstgroupsudo"
          no_passwd: false
          from_hosts: ALL
          as_user: ALL
          as_group: ALL
          commands:
            - /usr/bin/tail -f /dev/null
            - /usr/bin/tail - f /dev/exit
          state: present
      


      
  roles:
    - role: claranet.sudo
