---
dependency:
  name: galaxy
driver:
  name: gce
  project_id: ops4ops-training-sandbox  # if not set, will default to env GCE_PROJECT_ID
  region: europe-west1  # REQUIRED
  network_name: vpc-singlevm  # specify if other than default
  subnetwork_name: vpc-singlevm  # specify if other than default
  vpc_host_project: ops4ops-training-sandbox  # if you use a shared vpc, set here the vpc host project. In that case, your GCP user needs the necessary permissions in the host project, see https://cloud.google.com/vpc/docs/shared-vpc#iam_in_shared_vpc
  username: b.bkwedou-ngameni # used to connect with ssh to the GCE instance, will default to 'molecule'
  auth_kind: application  # set to machineaccount or serviceaccount or application - if set to null will read env GCP_AUTH_KIND
  #service_account_email: b.bkwedou-ngameni@fr.clara.net  # set to an email associated with the project - if set to null, will default to GCP_SERVICE_ACCOUNT_EMAIL. Should not be set if using auth_kind serviceaccount.
  #service_account_file: /home/delbechir/.config/gcloud/application_default_credentials.json  # set to the path to the JSON credentials file - if set to null, will default to env GCP_SERVICE_ACCOUNT_FILE
  scopes:
    - "https://www.googleapis.com/auth/compute"  # will default to env GCP_SCOPES, https://www.googleapis.com/auth/compute is the minimum required scope.
  external_access: true  # chose whether to create a public IP for the VM or not - default is private IP only
  instance_os_type: linux  # Either windows or linux. Will be considered linux by default. You can NOT mix Windows and Linux VMs in the same scenario.
platforms:
  - name: molecule-gce  #  REQUIRED: this will be your VM name
    zone: europe-west1-b  # Example: us-west1-b. Will default to zone b of region defined in driver (some regions do not have a zone-a)
    machine_type: n2d-highcpu-2  # If not specified, will default to n1-standard-1
    preemptible: false  # If not specified, will default to false. Preemptible instances have no SLA, in case of resource shortage in the zone they might get destroyed (or not be created) without warning, and will always be terminated after 24 hours. But they cost less and will mitigate the financial consequences of a PAYG licenced VM that would be forgotten.
    image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-minimal-2004-lts'  # Points to an image, you can get a list of available images with command 'gcloud compute images list'.
       # The expected format of this string is projects/<project>/global/images/family/<family-name>
       # (see https://googlecloudplatform.github.io/compute-image-tools/daisy-automating-image-creation.html)
       #  Wille default to debian-10 image for os_type Linux, Windows 2019 for os_type Windows
    tags: # Not required. Format must follow https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_instance_module.html#parameter-tags
      items:      
        - allow-ssh
        - allow-rdp

playbooks:
  

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_FORCE_COLOR: "true"
  options:
    v: true

verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    verbose: true
    s: true

lint: |
  set -e
  yamllint .
  ansible-lint
